 //
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@protocol TMAInsertPopoverContentViewControllerDelegate <NSObject>
- (void)insertEditablePathForDrawableInfo:(id)arg1;
- (id)editorForInsertingDrawables:(id)arg1 insertionContext:(id)arg2;
- (id)insertPopoverContentViewControllerCanvasEditor:(id)arg1;
- (id)insertPopoverContentViewControllerDrawableFactory:(id)arg1;
- (id)insertPopoverViewControllerDocumentRoot:(id)arg1;

- (id)interactiveCanvasController;
@end

//@interface
//@end

